document.write("<div class='aside-dropdown'>");
document.write("<div class='aside-dropdown__inner'>");
document.write("<span class='aside-dropdown__close'>");
document.write("<svg class='icon'>");
document.write("<i class='fa fa-times' aria-hidden='true'></i>");
document.write("</svg>");
document.write("</span>");
document.write("<div class='aside-dropdown__item d-lg-none d-block'>");
document.write("<ul class='aside-menu'>");
document.write("<li class='aside-menu__item'>");
document.write("<a class='aside-menu__link' href='#'><span>Home</span></a>");
document.write("</li>");
document.write("<li class='aside-menu__item'><a class='aside-menu__link' href='#'><span>About Us</span></a></li>");
document.write("<li class='aside-menu__item aside-menu__item--has-child'>");
document.write("<a class='aside-menu__link' href='javascript:void(0);'><span>Pages</span></a>");
document.write("<ul class='aside-menu__sub-list'>");
document.write("<li><a href='#'><span>About</span></a></li>");
document.write("<li><a href='#'> <span>Typography</span></a></li>");
document.write("<li><a href='#'><span>Donors & Partners</span></a></li>");
document.write("<li><a href='#'><span>Become a Volunteer</span></a></li>");
document.write("<li><a href='#'><span>Events</span></a></li>");
document.write("<li><a href='#'><span>Event Details</span></a></li>");
document.write("<li><a href='#'><span>Stories</span></a></li>");
document.write("<li><a href='#'><span>Story Details</span></a></li>");
document.write("<li><a href='#'><span>Blog</span></a></li>");
document.write("<li><a href='#'><span>Blog Post</span></a></li>");
document.write("<li><a href='#'><span>Gallery</span></a></li>");
document.write("<li><a href='#'><span>Pricing Plans</span></a></li>");
document.write("<li><a href='#'><span>FAQ</span></a></li>");
document.write("<li><a href='#'><span>404 Page</span></a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class='aside-menu__item aside-menu__item--has-child'>");
document.write("<a class='aside-menu__link' href='javascript:void(0);'><span>Causes</span></a>");
document.write("<ul class='aside-menu__sub-list'>");
document.write("<li><a href='#'><span>Causes 1</span></a></li>");
document.write("<li><a href='#'> <span>Causes 2</span></a></li>");
document.write("<li><a href='#'><span>Causes 3</span></a></li>");
document.write("<li><a href='#'><span>Cause Details</span></a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class='aside-menu__item aside-menu__item--has-child'>");
document.write("<a class='aside-menu__link' href='javascript:void(0);'><span>Shop</span></a>");
document.write("<ul class='aside-menu__sub-list'>");
document.write("<li><a href='#'><span>Catalog Page</span></a></li>");
document.write("<li><a href='#'><span>Shop Product</span></a></li>");
document.write("<li><a href='#'><span>Shop Cart</span></a></li>");
document.write("<li><a href='#'><span>Shop Checkout</span></a></li>");
document.write("<li><a href='#'><span>Shop Account</span></a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class='aside-menu__item'><a class='aside-menu__link' href='#'><span>Contacts</span></a></li>");
document.write("<li class='aside-menu__item aside-menu__item--has-child'>");
document.write("<a class='aside-menu__link' href='javascript:void(0);'><span>Elements</span></a>");
document.write("<ul class='aside-menu__sub-list'>");
document.write("<li><a href='#'><span>Alerts</span></a></li>");
document.write("<li><a href='#'><span>Team</span></a></li>");
document.write("<li><a href='#'><span>Testimonials</span></a></li>");
document.write("<li><a href='#'><span>Accordion</span></a></li>");
document.write("<li><a href='#'><span>Tabs</span></a></li>");
document.write("<li><a href='#'><span>Pricing Plan</span></a></li>");
document.write("<li><a href='#'><span>Counters</span></a></li>");
document.write("<li><a href='#'><span>Icons</span></a></li>");
document.write("</ul>");
document.write("</li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='aside-dropdown__item'>");
document.write("<ul class='aside-menu'>");
document.write("<li class='aside-menu__item'><a class='aside-menu__link' href='#'>Documents</a></li>");
document.write("<li class='aside-menu__item'><a class='aside-menu__link' href='#'>Information</a></li>");
document.write("<li class='aside-menu__item'><a class='aside-menu__link' href='#'>Our Team</a></li>");
document.write("<li class='aside-menu__item'><a class='aside-menu__link' href='#'>Be a Volunteer</a></li>");
document.write("</ul>");
document.write("<div class='aside-inner'><span class='aside-inner__title'>Email</span><a class='aside-inner__link' href='#'>info@karmafoundation.co</a></div>");
document.write("<div class='aside-inner'><span class='aside-inner__title'>Phone numbers</span><a class='aside-inner__link' href='tel:+180012345678'>+91 98984 00312</a>");
document.write("</div>");
document.write("<ul class='aside-socials'>");
document.write("<li class='aside-socials__item'><a class='aside-socials__link' href='#'><i class='fa fa-instagram' aria-hidden='true'></i></a></li>");
document.write("<li class='aside-socials__item'><a class='aside-socials__link' href='#'><i class='fa fa-google-plus' aria-hidden='true'></i></a></li>");
document.write("<li class='aside-socials__item'><a class='aside-socials__link aside-socials__link--active' href='#'><i class='fa fa-twitter' aria-hidden='true'></i></a></li>");
document.write("<li class='aside-socials__item'><a class='aside-socials__link' href='#'><i class='fa fa-facebook' aria-hidden='true'></i></a></li>");
document.write("</ul>");
document.write("</div>");
document.write("<div class='aside-dropdown__item'><a class='button button--squared' href='#'><span>Donate</span></a></div>");
document.write("</div>");
document.write("</div>");
document.write("<header class='header header--front'>");
document.write("<div class='container-fluid'>");
document.write("<div class='row no-gutters justify-content-between'>");
document.write("<div class='col-auto d-flex align-items-center'>");
document.write("<div class='dropdown-trigger d-none d-sm-block'>");
document.write("<div class='dropdown-trigger__item'></div>");
document.write("</div>");
document.write("<div class='header-logo'><a class='header-logo__link' href='index.html'><img class='header-logo__img logo--light' src='assets/images/logo_white.png' alt='logo'/><img class='header-logo__img logo--dark' src='assets/images/logo.png' alt='logo'/></a></div>");
document.write("</div>");
document.write("<div class='col-auto'>");
document.write("<nav>");
document.write("<ul class='main-menu'>");
document.write("<li class='main-menu__item'><a class='main-menu__link' href='#'><span>Home</span></a></li>");
document.write("<li class='main-menu__item'><a class='main-menu__link' href='#'><span>About Us</span></a></li>");
document.write("<li class='main-menu__item main-menu__item--has-child'>");
document.write("<a class='main-menu__link' href='javascript:void(0);'><span>Karma Communities</span></a>");
document.write("<ul class='main-menu__sub-list'>");
document.write("<li><a href='#'><span>Ahmedabad Book Club</span></a></li>");
document.write("<li><a href='#'><span>Gujarati Book Club</span></a></li>");
document.write("<li><a href='#'><span>Pi Club</span></a></li>");
document.write("<li><a href='#'><span>The Science Club</span></a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class='main-menu__item main-menu__item--has-child'>");
document.write("<a class='main-menu__link' href='javascript:void(0);'><span>Karma Assistance</span></a>");
document.write("<ul class='main-menu__sub-list'>");
document.write("<li><a href='#'><span>Shuruaat</span></a></li>");
document.write("<li><a href='#'> <span>Jeevan Shrishti </span></a></li>");
document.write("<li><a href='#'><span>Satya Sai School visit</span></a></li>");
document.write("<li><a href='#'><span>Shishu Gruh</span></a></li>");
document.write("<li><a href='#'><span>Correction Home</span></a></li>");
document.write("<li><a href='#'><span>Sahara</span></a></li>");
document.write("<li><a href='#'><span>Neev</span></a></li>");
document.write("</ul>");
document.write("</li>");
document.write("<li class='main-menu__item'><a class='main-menu__link' href='#'><span>Events</span></a></li>");
document.write("<li class='main-menu__item'><a class='main-menu__link' href='#'><span>Contacts</span></a></li>");
document.write("</ul>");
document.write("</nav>");
document.write("</div>");
document.write("<div class='col-auto d-flex align-items-center'>");
document.write("<div class='dropdown-trigger d-block d-sm-none'>");
document.write("<div class='dropdown-trigger__item'></div>");
document.write("</div>");
document.write("<a class='button button--squared' href='#'><span>Donate</span></a>");
document.write("</div>");
document.write("</div>");
document.write("</div>");
document.write("</header>");